#
# _config.yml for AWS Icons
#

exclude: [ "CNAME", "**/*_src*" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
production_url: https://sensa-emoji.svg.zone
title: Sensa Emoji
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
theme: null
links:
  - name: Sensa website
    url: "https://sensa.co/emoji"
  - name: Download originals
    url: "https://github.com/sensadesign/sensaemoji"
  - name: Report an issue
    url: "https://github.com/AwesomeLogos/sensa-emoji/issues"
